sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

install:
  - "pip install ."
  - "pip install coveralls"

script:
  - coverage run --source=vipaccess setup.py test

after_success:
  - coveralls
